{% set name = "dep-logic" %}
{% set version = "0.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dep_logic-{{ version }}.tar.gz
  sha256: 6be51b8a51893e67961a5c10ed7b8dd95fffe3ee42982fbb99f68218221a6ad2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pdm-backend
    - pip
  run:
    - python >=3.8
    - packaging >=22

test:
  imports:
    - dep_logic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pdm-project/dep-logic
  summary: Python dependency specifications supporting logical operations
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
